# Travis CI Build Script
notifications:
  slack: kissmyapp:ODLqzPLHklVTMNDvIF9VUSke
language: node_js
node_js:
  - "node"
services:
  - mongodb
script:
  - npm install
deploy:
  provider: gae
  keyfile: kiss-my-app-29c0b19a8d6d.json
  project: kiss-my-app
  on: develop
deploy:
  provider: gae
  keyfile: kiss-my-app-a1b50b7df125.json
  project: kiss-my-app
  on: master